# constitutive : The Constitutive Library

This notebook provide the functions that define the different stiffness tensors considering a Voigt notation

In [4]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
from simcoon import simmit as sim
import os

## L_iso

Provides the elastic stiffness tensor for an isotropic material.
The two first arguments are a couple of elastic properties. The third argument specifies which couple has been provided and the nature and order of coefficients.
Exhaustive list of possible third argument :
‘Enu’,’nuE,’Kmu’,’muK’, ‘KG’, ‘GK’, ‘lambdamu’, ‘mulambda’, ‘lambdaG’, ‘Glambda’.
Return a numpy ndarray.
Example :

In [5]:
E = 70000.0
nu = 0.3
L = sim.L_iso(E,nu,"Enu")
print(np.array_str(L, precision=2, suppress_small=True))

d = sim.check_symetries(L)
print(d['umat_type'])
print(d['props'])

x = sim.L_iso_props(L)
print(x)



[[94230.77 40384.62 40384.62     0.       0.       0.  ]
 [40384.62 94230.77 40384.62     0.       0.       0.  ]
 [40384.62 40384.62 94230.77     0.       0.       0.  ]
 [    0.       0.       0.   26923.08     0.       0.  ]
 [    0.       0.       0.       0.   26923.08     0.  ]
 [    0.       0.       0.       0.       0.   26923.08]]
ELISO
[7.e+04 3.e-01]
[7.e+04 3.e-01]


## M_iso

Provides the elastic compliance tensor for an isotropic material.
The two first arguments are a couple of elastic properties. The third argument specify which couple has been provided and the nature and order of coefficients.
Exhaustive list of possible third argument :
‘Enu’,’nuE,’Kmu’,’muK’, ‘KG’, ‘GK’, ‘lambdamu’, ‘mulambda’, ‘lambdaG’, ‘Glambda’.

In [ ]:
E = 70000.0
nu = 0.3
M = sim.M_iso(E,nu,"Enu")
print(np.array_str(M, suppress_small=True))

L_inv = np.linalg.inv(M)
d = sim.check_symetries(L_inv)
print(d['umat_type'])
print(d['props'])

x = sim.M_iso_props(M)
print(x)


## L_cubic

Provides the elastic stiffness tensor for a cubic material. Arguments are the stiffness coefficients C11, C12 and C44, or the elastic constants E, nu, G
Exhaustive list of possible third argument : ‘Cii’,’EnuG, the by-default argument is 'Cii'

In [7]:
E = 70000.0
nu = 0.3
G = 23000.0
L = sim.L_cubic(E,nu,G,"EnuG")
print(np.array_str(L, precision=2, suppress_small=True))

d = sim.check_symetries(L)
print(d['umat_type'])
print(d['props'])

x = sim.L_cubic_props(L)
print(x)

C11 = np.random.uniform(10000., 100000.)
C12 = np.random.uniform(10000., 100000.)
C44 = np.random.uniform(10000., 100000.)
Liso = sim.L_cubic(C11,C12,C44, "Cii")


[[94230.77 40384.62 40384.62     0.       0.       0.  ]
 [40384.62 94230.77 40384.62     0.       0.       0.  ]
 [40384.62 40384.62 94230.77     0.       0.       0.  ]
 [    0.       0.       0.   23000.       0.       0.  ]
 [    0.       0.       0.       0.   23000.       0.  ]
 [    0.       0.       0.       0.       0.   23000.  ]]
ELCUB
[7.0e+04 3.0e-01 2.3e+04]
[7.0e+04 3.0e-01 2.3e+04]


## M_cubic

Provides the elastic compliance tensor for a cubic material. Arguments are the stiffness coefficients C11, C12 and C44, or the elastic constants E, nu, G
Exhaustive list of possible third argument : ‘Cii’,’EnuG, the by-default argument is 'Cii'

In [ ]:
E = 70000.0
nu = 0.3
G = 23000.0
M = sim.M_cubic(E,nu,G,"EnuG")
print(np.array_str(M, suppress_small=True))

L = np.linalg.inv(M)
d = sim.check_symetries(L)
print(d['umat_type'])
print(d['props'])

x = sim.L_cubic_props(L)
print(x)

## L_isotrans

Provides the elastic stiffness tensor for an isotropic transverse material.
Arguments are longitudinal Young modulus EL, transverse young modulus, Poisson’s ratio for loading along the longitudinal axis nuTL, Poisson’s ratio for loading along the transverse axis nuTT, shear modulus GLT and the axis of symmetry.

In [ ]:
EL = 70000.0
ET = 20000.0
nuTL = 0.08
nuTT = 0.3
GLT = 12000.0
axis = 3
L = sim.L_isotrans(EL,ET,nuTL,nuTT,GLT,axis)
print(np.array_str(L, precision=2, suppress_small=True))

d = sim.check_symetries(L)
print(d['umat_type'])
print(d['axis'])
print(np.array_str(d['props'], precision=2, suppress_small=True))

x = sim.L_isotrans_props(L,axis)
print(np.array_str(x, precision=2))

    bp::def("L_iso", L_iso);
    bp::def("M_iso", M_iso);
    bp::def("L_cubic", L_cubic);
    bp::def("M_cubic", M_cubic);
    bp::def("L_ortho", L_ortho);
    bp::def("M_ortho", M_ortho);
    bp::def("L_isotrans", L_isotrans);
    bp::def("M_isotrans", M_isotrans);
    
    bp::def("check_symetries", check_symetries);
    bp::def("L_iso_props", L_iso_props);
    bp::def("M_iso_props", M_iso_props);
    bp::def("L_isotrans_props", L_isotrans_props);
    bp::def("M_isotrans_props", M_isotrans_props);
    bp::def("L_cubic_props", L_cubic_props);
    bp::def("M_cubic_props", M_cubic_props);
    bp::def("L_ortho_props", L_ortho_props);
    bp::def("M_ortho_props", M_ortho_props);
    bp::def("M_aniso_props", M_aniso_props);

## M_isotrans

Provides the elastic compliance tensor for an isotropic transverse material.
Arguments are longitudinal Young modulus EL, transverse young modulus, Poisson’s ratio for loading along the longitudinal axis nuTL, Poisson’s ratio for loading along the transverse axis nuTT, shear modulus GLT and the axis of symmetry.

In [ ]:
EL = 70000.0
ET = 20000.0
nuTL = 0.08
nuTT = 0.3
GLT = 12000.0
axis = 3
M = sim.M_isotrans(EL,ET,nuTL,nuTT,GLT,axis)
print(np.array_str(M, suppress_small=True))

x = sim.M_isotrans_props(M,axis)
print(np.array_str(x, precision=2, suppress_small=True))

## L_ortho

Provides the elastic stiffness tensor for an orthotropic material.
Arguments are either (convention 'EnuG'):

1. The Young modulus of axis 1 $E_1$,
2. The Young modulus of axis 2 $E_2$,
3. The Young modulus of axis 3 $E_3$,
4. The Poisson ratio of direction 1 with respect to 2 $\nu_{12}$,
5. The Poisson ratio of direction 1 with respect to 3 $\nu_{13}$,
6. The Poisson ratio of direction 2 with respect to 3 $\nu_{13}$,
7. The shear modulus of direction 1 with respect to 2 $G_{12}$,
8. The shear modulus of direction 1 with respect to 3 $G_{13}$,
9. The shear modulus of direction 2 with respect to 3 $G_{23}$,
10. The axial coefficient of thermal expansion in direction 1 $\alpha_1$,
11. The axial coefficient of thermal expansion in direction 1 $\alpha_2$,
12. The axial coefficient of thermal expansion in direction 1 $\alpha_3$,

or the list of Cii (C11, C12, C13, C22, C23, C33, C44, C55, C66) (convention 'Cii')

In [ ]:
E_1 = 4500.0
E_2 = 2300.0
E_3 = 2700.0
nu_12 = 0.06
nu_13 = 0.08
nu_23 = 0.3
G_12 = 2200.0
G_13 = 2100.0
G_23 = 2400.0

L = sim.L_ortho(E_1,E_2,E_3,nu_12,nu_13,nu_23,G_12,G_13,G_23,'EnuG')
print(np.array_str(L, precision=2, suppress_small=True))

d = sim.check_symetries(L)
print(d['umat_type'])
print(d['axis'])
print(np.array_str(d['props'], precision=2, suppress_small=True))

x = sim.L_ortho_props(L)
print(np.array_str(x, precision=2, suppress_small=True))

## M_ortho

Provides the elastic compliance tensor for an orthotropic material.
Arguments are either (convention 'EnuG'):

1. The Young modulus of axis 1 $E_1$,
2. The Young modulus of axis 2 $E_2$,
3. The Young modulus of axis 3 $E_3$,
4. The Poisson ratio of direction 1 with respect to 2 $\nu_{12}$,
5. The Poisson ratio of direction 1 with respect to 3 $\nu_{13}$,
6. The Poisson ratio of direction 2 with respect to 3 $\nu_{13}$,
7. The shear modulus of direction 1 with respect to 2 $G_{12}$,
8. The shear modulus of direction 1 with respect to 3 $G_{13}$,
9. The shear modulus of direction 2 with respect to 3 $G_{23}$,
10. The axial coefficient of thermal expansion in direction 1 $\alpha_1$,
11. The axial coefficient of thermal expansion in direction 1 $\alpha_2$,
12. The axial coefficient of thermal expansion in direction 1 $\alpha_3$,

or the list of Cii (C11, C12, C13, C22, C23, C33, C44, C55, C66) (convention 'Cii')

In [ ]:
E_1 = 4500.0
E_2 = 2300.0
E_3 = 2700.0
nu_12 = 0.06
nu_13 = 0.08
nu_23 = 0.3
G_12 = 2200.0
G_13 = 2100.0
G_23 = 2400.0

M = sim.M_ortho(E_1,E_2,E_3,nu_12,nu_13,nu_23,G_12,G_13,G_23,'EnuG')
print(np.array_str(M, suppress_small=True))

x = sim.M_ortho_props(M)
print(np.array_str(x, precision=4, suppress_small=True))

In [6]:
L = sim.L_iso(70000.0, 0.3,"Enu");
Eel = np.random.uniform(0., 1., 6);
ndi = 3
sigma =  sim.el_pred(L, Eel, ndi)


AttributeError: module 'simcoon.simmit' has no attribute 'el_pred'

In [9]:
E = 70000.0
nu = 0.3
L = sim.L_iso(E,nu,"Enu")